dist: focal
language: python
sudo: required
addons:
  chrome: stable
env:
  global:
  - secure: EVObCafLubboW7PQ69OhLI9qSMWDUYuL8EvXCX2MsBzlgX1W6cc62IJbKV87EHOnu/2KgHXYNVYN4rmydVbOU+nMHwtryf8+utNcyuDp40kKoNjWhWue++AheXgAjUt1lON4/kiZ5gxEupQeEXDPvP/5LrUuDUEQRwJa6pbivD8=
  - secure: KOpU31rbmwrjGovRX769F9H1/+KdtB5KJfMKIMRZPTeaH/zrlUDaTh9lBOkAFD1S/0nagsrXIUq9e9PJD3pEWze09VUK0mivCl96/ZXFt605UJXSKgWvZNJdRLexzwPhHd/MDzbMqTfrAlN6x9OSA5uIOaGzaQSZjkXjed8IkRk=
  - secure: PIru5LiKivChzeac7fpeT6PTnacjbf03HE7IIjwYcU255rAmeSVkjZFC7Ka1UIZqaMlIrg6STCMM9SN3T9SmW2z7LJ4PTqHMW1VUWWhdN7xO/df3tZH6J0oqFvnVbH40soTkaDATE/J/7N1oCxdMeBTEGgRJxkjmsgIj/4YJSSE=
#Tokens order: SAUSE_USERNAME, SAUCE_TOKEN, CODACY_API_TOKEN
matrix:
  fast_finish: true
  include:
  - env: GLTEST='test' CODACY=true
  - env: GLTEST='build_and_install' DISTRIBUTION='buster'
  - env: GLTEST='build_and_install' DISTRIBUTION='focal'
before_install:
- nvm install stable
- nvm use stable
install: true
script:
- "$TRAVIS_BUILD_DIR/travis/script.sh"
notifications:
  slack:
    secure: KhvVUD69Pq/0ZuQyug+NfH8LXLwFNlBQmhgAx6woYtnpGwq5KqMl4lpNeb1dKptUlJen+iAQRwO6nqAzWL92eO9qSCSLZDvKS0qDtMUAI9ax1cJ/G8K/Ee6vILU6id37VtwHFD4cJQPxZOZoDXoNcO6PRGVJDFt6JTGsOroexCI=
